# Bootstrap the strike ci/cd tool.
#
# Stage 0 is "dirty" in two aspects:
# - it uses a legacy Containerfile
# - it still needs an implicit shell expansion in one of the Containerfile steps
#
# Stage 0 creates a "dirty" stage 1 container with podman and strike in it.
# This stage 1 container then uses the "dirty" strike to:
# - build a stage 2 container
# - use the stage 2 container to build a stage 3 container
# - release the stage 2 container if it is identical to stage 3
#
# Prerequisite: you have podman installed on your host.
#
# GIT_COMMIT=<commit-sha> ; podman build -t strike:stage_1 --build-arg GIT_COMMIT=${GIT_COMMIT} https://raw.githubusercontent.com/istr/strike/${GIT_COMMIT}/bootstrap/Containerfile
# podman run --env COSIGN_PRIVATE_KEY --env COSIGN_PASSWORD --security-opt unmask=/proc/* --mount type=tmpfs,dst=/podman/.local/share/containers/storage,U --userns=keep-id strike:stage_1
#
FROM docker.io/library/golang:1.26.8-alpine@sha256:6e5de3f5b9fb7e30b8bb2ffe8dcbcbdaa2990f0f31267456eabe83f870a623be AS builder
ARG GIT_COMMIT
RUN ["apk", "add", "--no-cache", "git"]
WORKDIR /src
RUN ["git", "init"]
# We want no-sh. However, we cannot pass GIT_COMMIT to git using ARG/ENV combination.
RUN git fetch --depth 1 https://github.com/istr/strike ${GIT_COMMIT}
RUN ["git", "checkout", "FETCH_HEAD"]
RUN ["go", "mod", "download"]
RUN ["go", "generate", "./contract"]
ENV CGO_ENABLED=0
RUN ["go", "build", "-trimpath", "-ldflags=-s -w", "-o", "strike", "./cmd/strike"]

FROM docker.io/mgoltzsche/podman@sha256:53e4c6d0597bd01afca2355b83d993c4254efce0e64afa0beb3026d38ee27a9d
COPY --from=builder /src /src

RUN rm -f /usr/bin/fuse-overlayfs /usr/bin/libfuse* /usr/local/bin/*fuse*
RUN printf "[storage]\ndriver = \"overlay\"\n" > /etc/containers/storage.conf

WORKDIR /src
ENTRYPOINT ["/src/strike"]
CMD ["run"]
