// Command genenums emits unexported typed const blocks for string-disjunction
// CUE definitions, as a sibling *_enum.gen.go beside the gengotypes output.
// Public CUE API only (cue/load + cue). It exists because cue exp gengotypes
// emits the named string type for a disjunction def but drops the disjunction's
// values; this pass recovers those values as constants so switches over the
// type can be exhaustiveness-checked. The generated file carries the standard
// generated-code header so golangci excludes it.
package main

import (
	"bytes"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"unicode"

	"cuelang.org/go/cue"
	"cuelang.org/go/cue/cuecontext"
	"cuelang.org/go/cue/load"
)

// internalDir maps a contract package dir to its generated Go home, mirroring
// the Makefile moves (attest's Go home is internal/deploy).
func internalDir(contractDir string) (dir, pkg string) {
	base := filepath.Base(contractDir)
	if base == "attest" {
		return "internal/deploy", "deploy"
	}
	return "internal/" + base, base
}

type enumDef struct {
	goType string
	values []string
}

func main() {
	if len(os.Args) < 2 {
		fmt.Fprintln(os.Stderr, "usage: genenums <contract-package-dir>...")
		os.Exit(2)
	}
	for _, arg := range os.Args[1:] {
		if err := generate(arg); err != nil {
			fmt.Fprintf(os.Stderr, "genenums %s: %v\n", arg, err)
			os.Exit(1)
		}
	}
}

func generate(contractDir string) error {
	ctx := cuecontext.New()
	insts := load.Instances([]string{contractDir}, &load.Config{})
	if len(insts) == 0 {
		return fmt.Errorf("no instances")
	}
	if insts[0].Err != nil {
		return insts[0].Err
	}
	pkgVal := ctx.BuildInstance(insts[0])
	if err := pkgVal.Err(); err != nil {
		return err
	}

	var defs []enumDef
	iter, err := pkgVal.Fields(cue.Definitions(true))
	if err != nil {
		return err
	}
	for iter.Next() {
		sel := iter.Selector()
		if !sel.IsDefinition() {
			continue
		}
		v := iter.Value()
		vals, ok := stringDisjuncts(v)
		if !ok {
			continue
		}
		defs = append(defs, enumDef{
			goType: goTypeName(sel, v),
			values: vals,
		})
	}
	if len(defs) == 0 {
		return nil
	}
	sort.Slice(defs, func(i, j int) bool { return defs[i].goType < defs[j].goType })

	dir, pkg := internalDir(contractDir)
	src := render(pkg, defs)
	formatted, err := format.Source(src)
	if err != nil {
		return fmt.Errorf("format: %w\n%s", err, src)
	}
	out := filepath.Join(dir, filepath.Base(dir)+"_enum.gen.go")
	if pkg == "deploy" {
		out = filepath.Join(dir, "deploy_enum.gen.go")
	}
	return os.WriteFile(out, formatted, 0o644)
}

// stringDisjuncts returns the concrete string disjuncts of v if v is a
// disjunction of concrete strings (with or without a default marker), else ok=false.
func stringDisjuncts(v cue.Value) (vals []string, ok bool) {
	op, args := v.Expr()
	if op != cue.OrOp || len(args) < 2 {
		return nil, false
	}
	for _, a := range args {
		if a.Kind() != cue.StringKind {
			return nil, false
		}
		s, err := a.String()
		if err != nil {
			return nil, false
		}
		vals = append(vals, s)
	}
	return vals, true
}

// goTypeName derives the Go type name gengotypes emits for the def: the @go
// attribute name if present, else the definition name without its leading '#'.
func goTypeName(sel cue.Selector, v cue.Value) string {
	if a := v.Attribute("go"); a.Err() == nil {
		if name, err := a.String(0); err == nil && name != "" {
			return name
		}
	}
	return strings.TrimPrefix(sel.String(), "#")
}

func render(pkg string, defs []enumDef) []byte {
	var b bytes.Buffer
	fmt.Fprintln(&b, "// Code generated by genenums. DO NOT EDIT.")
	fmt.Fprintln(&b)
	fmt.Fprintf(&b, "package %s\n\n", pkg)
	fmt.Fprintln(&b, "const (")
	for _, d := range defs {
		for _, val := range d.values {
			fmt.Fprintf(&b, "\t%s %s = %q\n", constIdent(d.goType, val), d.goType, val)
		}
	}
	fmt.Fprintln(&b, ")")
	return b.Bytes()
}

// constIdent builds the unexported constant identifier: lowerFirst(goType) plus
// the CamelCased value. "spdx-json" -> "SpdxJson"; "file" -> "File".
func constIdent(goType, val string) string {
	return lowerFirst(goType) + camel(val)
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	r[0] = unicode.ToLower(r[0])
	return string(r)
}

func camel(s string) string {
	parts := strings.FieldsFunc(s, func(r rune) bool { return r == '-' || r == '_' })
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		r := []rune(p)
		r[0] = unicode.ToUpper(r[0])
		b.WriteString(string(r))
	}
	return b.String()
}
